linting and formatting config updates

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,14 +7,14 @@ if [ $? -eq 0 ]; then
   echo "\033[0;32mFormatting passed.\033[0m"
 fi
 
-# pnpm run lint
-# if [ $? -ne 0 ]; then
-#   echo "\033[0;31mLinting failed. Push aborted.\033[0m"
-#   exit 1
-# fi
-# if [ $? -eq 0 ]; then
-#   echo "\033[0;32mLinting passed.\033[0m"
-# fi
+pnpm run lint
+if [ $? -ne 0 ]; then
+  echo "\033[0;31mLinting failed. Push aborted.\033[0m"
+  exit 1
+fi
+if [ $? -eq 0 ]; then
+  echo "\033[0;32mLinting passed.\033[0m"
+fi
 
 # pnpm run build
 # if [ $? -ne 0 ]; then
